name: Déploiement automatique vers Back4app

on:
  push:
    branches:
      - main
    paths:
      - "cloud/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Déployer le Cloud Code sur Back4app
        uses: docker://raschidjfr/b4a-deploy:latest
        env:
          B4A_ACCOUNT_KEY: ${{ secrets.BACK4APP_ACCOUNT_KEY }}
          B4A_APP_NAME: "Docly"
          CLOUD_PATH: "cloud"
          
